//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEFHaciendaCañaveral.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCEFHaciendaCañaveral.Language.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosotros.
        /// </summary>
        public static string ACERCA_DE {
            get {
                return ResourceManager.GetString("ACERCA_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string ACERCADE_HISTORIA {
            get {
                return ResourceManager.GetString("ACERCADE_HISTORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misión.
        /// </summary>
        public static string ACERCADE_MISION {
            get {
                return ResourceManager.GetString("ACERCADE_MISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros valores.
        /// </summary>
        public static string ACERCADE_NUESTROS_VALORES {
            get {
                return ResourceManager.GetString("ACERCADE_NUESTROS_VALORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivos.
        /// </summary>
        public static string ACERCADE_OBJETIVOS {
            get {
                return ResourceManager.GetString("ACERCADE_OBJETIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visión.
        /// </summary>
        public static string ACERCADE_VISION {
            get {
                return ResourceManager.GetString("ACERCADE_VISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mas.
        /// </summary>
        public static string BTN_MAS {
            get {
                return ResourceManager.GetString("BTN_MAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string CONTACTOS {
            get {
                return ResourceManager.GetString("CONTACTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string INICIO {
            get {
                return ResourceManager.GetString("INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgánicos.
        /// </summary>
        public static string ORGANICOS {
            get {
                return ResourceManager.GetString("ORGANICOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso de elaboración.
        /// </summary>
        public static string PROCESO_DE_ELABORACION {
            get {
                return ResourceManager.GetString("PROCESO_DE_ELABORACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string SERVICIOS {
            get {
                return ResourceManager.GetString("SERVICIOS", resourceCulture);
            }
        }
    }
}
